# Generated by Django 6.0.6 on 2026-06-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_product_cat_name_4f76a1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
