# Generated by Django 6.0.6 on 2026-06-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_is_best_seller_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
    ]
