# Generated by Django 6.0.6 on 2026-06-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pos_order',
            field=models.BooleanField(default=False),
        ),
    ]
